build:
    script:
        - cd frontend
        - npm set progress=false
        - yarn
        - npm run prod
        - cp -r lib/img dist/lib
        # - npm test
        - cd ../backend
        - mvn --errors -B -U clean verify -Pfinal-war
    cache:
        key: node_modules
        paths:
            - frontend/node_modules
    except:
        - master@tbmb/NuitInfo2016

build-deploy:
    script:
        - cd frontend
        - npm set progress=false
        - yarn
        - npm run prod
        - cp -r lib/img dist/lib
        # - npm test
        - cd ../backend
        - mvn --errors -B -U clean verify -Pfinal-war
        - cp target/backend.war /var/lib/tomcat8/webapps/ROOT.war
    cache:
        key: node_modules
        paths:
            - frontend/node_modules
    only:
        - master@tbmb/NuitInfo2016
